version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_HOST=postgres
      - JAVA_HOME=/opt/java/openjdk
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./reports:/app/reports
      - ./test:/app/test
    depends_on:
      - postgres
    command: npm run start:debug

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jasper_reports_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  jasper:
    image: openjdk:17
    env_file:
      - .env
    volumes:
      - ./uploads:/app/${UPLOAD_DIR:-uploads}
      - ./jasper-engine:/app/${JASPER_ENGINE_DIR:-jasper-engine}

volumes:
  postgres_data: